### ISSUE TITLE
when will the paper public avaliable?

### ISSUE THREAD

**Issue by ShiyangZhang** [Biano-AI/serving-compare-middleware#9]
Hi, guys, when will the paper public avaliable?

**Comment by illagrenan** [comment]
We would like to release a traditional paper by the end of this year, but it will depend on the overall utilization of the team.

We have published our findings on our blog:

* https://biano-ai.github.io/research/2021/08/16/quantitative-comparison-of-serving-platforms-for-neural-networks.html
* https://biano-ai.github.io/research/2021/10/15/quantitative-comparison-of-serving-platforms-for-neural-networks-part-2.html

**Comment by ShiyangZhang** [comment]
> utilization

look forward to it！
